### ISSUE TITLE
My Hosted UI Link - Login URL is not being encoded functionally

### ISSUE THREAD

**Issue by ghost** [Dmbob/plex-oauth#16]
Here is the Plex Documentation I could find on the OAuth Process:
https://forums.plex.tv/t/authenticating-with-plex/609370

it details a final encoded URL like:
https://app.plex.tv/auth#?clientID=<clientIdentifier>&code=pinCode>&context%5Bdevice%5D%5Bproduct%5D=My%20Cool%20Plex%20App&forwardUrl=https%3A%2F%2Fmy-cool-plex-app.com

My URL that is being generated is in this format:
https://app.plex.tv/auth#?#?code=Redacted&context[device][product]=APP&context[device][device]=Device&clientID=Redacted&forwardUrl=Redacted

The URL I was getting wasn't working for me, so I made this below change and now it is working

I'm not sure if the alternate method of URL encoding is valid or not, but I adjusted the content of the PlexOauth.js folder and incorporated the qs package mentioned in the plex documentation, and passed it in an object format instead of building the URL manually

if you want the change I made to PlexOauth just let me know and I can submit a PR

**Comment by LukasParke** [comment]
reverted my change back and the Oauth is still working fine, seems like my issue was more the redirect URL on the other issue I opened

**Comment by Dmbob** [comment]
I'll look into this, it might be better to have it URL encoded anyway.

I know I didn't run into any issues without it, but there may be some cases where it is better.

Thanks for sharing!
