### ISSUE TITLE
Add warnings if forward URL is non-standard (Electron deep link formats like electron-fiddle://)

### ISSUE THREAD

**Issue by ghost** [Dmbob/plex-oauth#17]
Plex Forums link:
https://forums.plex.tv/t/forwardurl-not-redirecting-for-non-http-https-urls-eg-my-app-plex-for-third-party-mobile-client/795347

The forwardURL cannot be anything other than http/https or the redirect is blocked by plex, additionally, if you provide a forwardURL that is invalid it scraps the entire authentication method and fails back to the main plex.tv homepage

**Comment by Dmbob** [comment]
Good catch, I'll look into adding a protocol check to this.

Thank you
