### ISSUE TITLE
Null or Undefined forwardUrl should equate to a blank string when generating the AuthUrl of URL is invalid

### ISSUE THREAD

**Issue by ghost** [Dmbob/plex-oauth#19]
I set my default input value to a blank string for the wrapper I'm working on.

**Comment by ghost** [comment]
should be menial to implement

**Comment by Dmbob** [comment]
This should be handled by Typescript, but good to have the check anyway. This actually highlights the issue that I did not make this parameter optional. So I will fix that as part of the pull request that you have opened.

**Comment by Dmbob** [comment]
Closed via #20
